### ISSUE TITLE
CI: use pipeline to release artifacts or docker iamges automatically

### ISSUE THREAD

**Issue by JaredTan95** [tricorder-observability/Starship#44]
**Is your feature request related to a problem? Please describe.**
We need to build images manually for each debug or when we develop. and those repetitive work consumes a lot of time.

**Describe the solution you'd like**
We can use GitHub actions to build those artifacts automatically and push to `github packages`

**Sub-tasks**
- [x] Move images to github package repo
- [x] #118
- [x] Replace github package with docker hub in helm-charts,https://github.com/tricorder-observability/helm-charts/pull/108
- [x] Create pipeline to release images to China mainland repos

**Comment by JaredTan95** [comment]
- https://github.com/tricorder-observability/starship/pull/85
- https://github.com/tricorder-observability/starship/pull/89
- https://github.com/tricorder-observability/starship/pull/93
- https://github.com/tricorder-observability/starship/pull/99
